### ISSUE TITLE
Boomerang replication on OP-TEE

### ISSUE THREAD

**Issue by nikoskoutr** [ucsb-seclab/boomerang#1]
Hello,

I am interested in replicating the boomerang attack on OP-TEE.
How would I approach the matter?
How a TA could access physical memory? 
I am currently studying your OP-TEE fork and the resolution for the vulnerability.
Any guideline is greatly appreciated.

Thank you for your time,
Nick

**Comment by Machiry** [comment]
Hi Nick, As we mentioned in the paper, OP-TEE doesn't have full-blown Boomerang attack.
The attacks were related to Leaking shared memory and corresponding issues are: https://github.com/linaro-swg/linux/issues/14 and https://github.com/linaro-swg/linux/issues/13

**Comment by nikoskoutr** [comment]
Thank you for your quick answer, as I can see the boomerang vulnerability is now fixed in OP-TEE.
Great work with finding this vulnerability.
Best regards,
Nick
